# Generated by Django 5.0.6 on 2024-06-27 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAcademy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='principal',
            name='numero_trabajador',
            field=models.IntegerField(verbose_name=12),
        ),
        migrations.AlterField(
            model_name='students',
            name='matricula',
            field=models.CharField(max_length=12),
        ),
        migrations.AddField(
            model_name='professor',
            name='category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='appAcademy.category'),
            preserve_default=False,
        ),
    ]
