# Generated by Django 5.0.6 on 2024-06-28 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAcademy', '0003_alter_professor_category_alter_professor_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
    ]
