# Generated by Django 5.0.6 on 2024-07-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPeriod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['id'], 'verbose_name': 'Periodo', 'verbose_name_plural': 'Cuatrimestre'},
        ),
        migrations.RemoveField(
            model_name='period',
            name='cicle',
        ),
        migrations.AddField(
            model_name='period',
            name='cycle',
            field=models.CharField(default='2024-2025', max_length=10, verbose_name='Ciclo'),
        ),
        migrations.AddField(
            model_name='period',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(choices=[('enero - abril', 'enero - abril'), ('mayo - agosto', 'mayo - agosto'), ('septiembre - diciembre', 'septiembre - diciembre')], max_length=25, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='period',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(max_length=2, verbose_name='Cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(max_length=10, verbose_name='Cuatrimestre en Letra'),
        ),
    ]
